<?php

use Budapest\Transport\TramLine;

$lines = [
    new TramLine(
        "1",
        "Bécsi út / Vörösvári út <> Kelenföld vasútállomás M",
        1984,
        "none",
        18.2,
    ),
    new TramLine(
        "1A",
        "Bécsi út / Vörösvári út <> Népliget M",
        2023,
        "none",
        11.2,
    ),
    new TramLine("2", "Jászai Mari tér <> Közvágóhíd H", 1945, "none", 6.0),
    new TramLine(
        "2B",
        "Jászai Mari tér <> Pesterzsébet, Pacsirtatelep",
        2022,
        "pesti",
        13.9,
    ),
    new TramLine(
        "3",
        "Mexikói út M <> Gubacsi út / Határ út",
        2001,
        "none",
        13.3,
    ),
    new TramLine(
        "4",
        "Széll Kálmán tér M <> Újbuda-központ M",
        1951,
        "none",
        8.5,
    ),
    new TramLine(
        "6",
        "Széll Kálmán tér <> Móricz Zsigmond körtér ",
        1945,
        "none",
        8.3,
    ),
    new TramLine(
        "12",
        "Angyalföld kocsiszín <> Rákospalota, Kossuth utca",
        1955,
        "none",
        4.7,
    ),
    new TramLine(
        "14",
        "Lehel tér M <> Káposztásmegyer, Megyeri út",
        1955,
        "none",
        11.1,
    ),
    new TramLine(
        "17",
        "Bécsi út / Vörösvári út <> Savoya Park",
        2016,
        "budai",
        14.7,
    ),
    new TramLine(
        "19",
        "Bécsi út / Vörösvári út <> Kelenföld vasútállomás M",
        1964,
        "budai",
        11.2,
    ),
    new TramLine(
        "23",
        "Jászai Mari tér <> Keleti pályaudvar M",
        2023,
        "pesti",
        9.4,
    ),
    new TramLine(
        "24",
        "Keleti pályaudvar M <> Közvágóhíd H",
        1951,
        "none",
        5.2,
    ),
    new TramLine(
        "28",
        "Blaha Lujza tér M (Népszínház utca) <> Izraelita temető",
        1950,
        "none",
        10.8,
    ),
    new TramLine(
        "28A",
        "Blaha Lujza tér M (Népszínház utca) <> Új köztemető (Kozma utca)",
        2016,
        "none",
        10.1,
    ),
    new TramLine(
        "37",
        "Blaha Lujza tér M (Népszínház utca) <> Új köztemető (Kozma utca)",
        1950,
        "none",
        9.7,
    ),
    new TramLine(
        "37A",
        "Blaha Lujza tér M (Népszínház utca) <> Sörgyár",
        1992,
        "none",
        5.9,
    ),
    new TramLine(
        "41",
        "Bécsi út / Vörösvári út <> Kamaraerdei Ifjúsági Park",
        1963,
        "budai",
        18.5,
    ),
    new TramLine(
        "42",
        "Határ út M <> Kispest, Tulipán utca",
        1959,
        "none",
        3.0,
    ),
    new TramLine("47", "Deák Ferenc tér M <> Városház tér", 1960, "none", 8.8),
    new TramLine("48", "Deák Ferenc tér M <> Savoya Park", 2014, "none", 8.0),
    new TramLine(
        "49",
        "Deák Ferenc tér M <> Kelenföld vasútállomás M",
        1945,
        "none",
        5.4,
    ),
    new TramLine(
        "50",
        "Határ út M <> Pestszentlőrinc, Béke tér",
        1945,
        "none",
        8.0,
    ),
    new TramLine(
        "51",
        "Mester utca / Ferenc körút <> Nagysándor József utca",
        2011,
        "none",
        8.2,
    ),
    new TramLine(
        "51A",
        "Mester utca / Ferenc körút <> Koppány utca",
        2011,
        "none",
        2.4,
    ),
    new TramLine(
        "52",
        "Határ út M <> Pesterzsébet, Pacsirtatelep",
        1980,
        "none",
        7,
    ),
    new TramLine("56", "Hűvösvölgy <> Városház tér", 2016, "budai", 17.1),
    new TramLine(
        "56A",
        "Hűvösvölgy <> Móricz Zsigmond körtér M",
        2016,
        "budai",
        11.3,
    ),
    new TramLine(
        "59",
        "Szent János Kórház <> Márton Áron tér",
        1945,
        "none",
        5.5,
    ),
    new TramLine(
        "59A",
        "Széll Kálmán tér M <> Márton Áron tér",
        2008,
        "none",
        4.2,
    ),
    new TramLine("59B", "Hűvösvölgy <> Márton Áron tér", 2016, "budai", 10.8),
    new TramLine(
        "60",
        "Városmajor <> Széchenyi-hegy, Gyermekvasút",
        1874,
        "none",
        3.7,
    ),
    new TramLine(
        "61",
        "Hűvösvölgy <> Móricz Zsigmond körtér M",
        1945,
        "budai",
        11,
    ),
    new TramLine(
        "62",
        "Rákospalota, MÁV-telep <> Blaha Lujza tér M (Népszínház utca)",
        1964,
        "none",
        13.7,
    ),
    new TramLine(
        "62A",
        "Rákospalota, MÁV-telep <> Kőbánya alsó vasútállomás (Mázsa tér)",
        2008,
        "none",
        9.2,
    ),
    new TramLine(
        "69",
        "Mexikói út M <> Újpalota, Erdőkerülő utca",
        1973,
        "none",
        6.5,
    ),
];
