<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Include="MikulasCukraszdaja_VB_Lib.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MikulasCukraszdaja_VB_Lib\MikulasCukraszdaja_VB_Lib.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="feladatok.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="keszites.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="sutemenyek.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
