"use strict";

const subjects = [
  {
    id: 1,
    name: "Mildred K. Gossamer",
    birth: "1974-03-22",
    occupation: "Lunch Lady",
    traits: [
      "mildly radioactive",
      "insists on feeding the cubes",
      "afraid of doors",
    ],
    course: "Aperture Science Handheld Portal Device Calibration",
    status: "alive",
  },
  {
    id: 2,
    name: "Trevor Binks",
    birth: "1988-09-10",
    occupation: "Intern (Unpaid)",
    traits: [
      "overly eager",
      "confuses walls with floors",
      "writes fan mail to GLaDOS",
    ],
    course: "Repulsion Gel Mobility Training",
    status: "terminated",
  },
  {
    id: 3,
    name: "Cynthia V. Doone",
    birth: "1962-01-04",
    occupation: "Motivational Speaker",
    traits: ["constantly optimistic", "motivates turrets", "believes in cubes"],
    course: "Thermal Discouragement Beam Evasion",
    status: "alive",
  },
  {
    id: 4,
    name: "Gary Lumen",
    birth: "1993-06-15",
    occupation: "Light Fixture Technician",
    traits: [
      "thinks light is sentient",
      "eats batteries",
      "glows slightly in the dark",
    ],
    course: "Hard Light Bridge Navigation",
    status: "terminated",
  },
  {
    id: 5,
    name: "Avery Moss",
    birth: "1979-12-01",
    occupation: "Freelance Philosopher",
    traits: [
      "asks cubes about morality",
      "deep thinker, shallow breath",
      "talks to walls",
    ],
    course: "Advanced Neurotoxin Avoidance",
    status: "alive",
  },
  {
    id: 6,
    name: "Elena T. Hark",
    birth: "1985-11-03",
    occupation: "Cake Decorator",
    traits: [
      "insists the cake is real",
      "tastes test chambers",
      "suspiciously cheerful",
    ],
    course: "Propulsion Gel Speed Test",
    status: "terminated",
  },
  {
    id: 7,
    name: "Bruce Melvin",
    birth: "1990-02-14",
    occupation: "Door-to-Door Salesman",
    traits: [
      "sells turrets door-to-door",
      "overly confident",
      "misses every portal shot",
    ],
    course: "Aerial Faith Plate Endurance Test",
    status: "terminated",
  },
  {
    id: 8,
    name: "Nina R. Grell",
    birth: "1971-08-19",
    occupation: "Professional Sleeper",
    traits: [
      "always napping mid-test",
      "claims dreams of Wheatley",
      "snoring causes vibrations",
    ],
    course: "Cryogenic Suspension Orientation",
    status: "alive",
  },
  {
    id: 9,
    name: "Felix Ormond",
    birth: "1982-04-07",
    occupation: "Conspiracy Theorist",
    traits: [
      "believes GLaDOS is his mother",
      "wears 4 tin-foil hats",
      "talks in binary sometimes",
    ],
    course: "Portal Gun Safety (Basic)",
    status: "alive",
  },
  {
    id: 10,
    name: "Tamara Sloane",
    birth: "1994-07-29",
    occupation: "Fitness Influencer",
    traits: [
      "streamed her entire testing",
      "calls portals 'gains rings'",
      "has 2 million turret followers",
    ],
    course: "Long Fall Boot Impact Studies",
    status: "alive",
  },
  {
    id: 11,
    name: "Ivan Drake",
    birth: "1987-02-11",
    occupation: "Janitor",
    traits: [
      "cleans neurotoxin vents",
      "hums Still Alive",
      "immune to sarcasm",
    ],
    course: "Companion Cube Maintenance Certification",
    status: "alive",
  },
  {
    id: 12,
    name: "Rebecca L. Trent",
    birth: "1978-05-16",
    occupation: "Unemployed (by choice)",
    traits: ["claims test chambers are art", "paints portals", "fears cubes"],
    course: "Excursion Funnel Dynamics",
    status: "terminated",
  },
  {
    id: 13,
    name: "Oscar Flint",
    birth: "1969-10-12",
    occupation: "Retired Astronaut",
    traits: [
      "keeps shouting 'SPAAAACE!'",
      "head permanently tilted upward",
      "nostalgic for zero gravity",
    ],
    course: "Aperture Space Core Interaction",
    status: "alive",
  },
  {
    id: 14,
    name: "Darla F. Knox",
    birth: "1980-09-03",
    occupation: "IT Support",
    traits: [
      "tries to reboot GLaDOS",
      "argues with turrets",
      "answers help tickets mid-test",
    ],
    course: "Aperture Mainframe Interface Basics",
    status: "terminated",
  },
  {
    id: 15,
    name: "Martin Poe",
    birth: "1977-06-25",
    occupation: "Poet",
    traits: [
      "writes haikus about portals",
      "rhymes under stress",
      "thinks Wheatley’s Britishness is poetic",
    ],
    course: "Neurotoxin Personality Retention Experiment",
    status: "alive",
  },
  {
    id: 16,
    name: "Holly Brine",
    birth: "1995-12-09",
    occupation: "Professional Swimmer",
    traits: [
      "swims through Repulsion Gel",
      "hates dry floors",
      "wears goggles at all times",
    ],
    course: "Repulsion Gel Deep Dive",
    status: "terminated",
  },
  {
    id: 17,
    name: "Eugene T. Marsh",
    birth: "1984-04-28",
    occupation: "Accountant",
    traits: [
      "counts test chambers aloud",
      "requests tax deductions for portals",
      "keeps ledgers on cube weights",
    ],
    course: "Weighted Storage Cube Logistics",
    status: "alive",
  },
  {
    id: 18,
    name: "Sandra Dune",
    birth: "1972-03-02",
    occupation: "Botanist",
    traits: [
      "plants in test chambers",
      "talks to algae",
      "tried to grow potatoes near GLaDOS",
    ],
    course: "Aperture Agriscience Initiative",
    status: "terminated",
  },
  {
    id: 19,
    name: "Harvey L. Keel",
    birth: "1965-11-30",
    occupation: "Lawyer",
    traits: [
      "claims legal immunity from turrets",
      "argues with announcer voice",
      "filed a lawsuit against gravity",
    ],
    course: "Aperture Legal Compliance Orientation",
    status: "terminated",
  },
  {
    id: 20,
    name: "Zoey Mirth",
    birth: "1991-01-18",
    occupation: "Game Tester",
    traits: [
      "speedruns test chambers",
      "accidentally broke physics once",
      "laughs maniacally at loading screens",
    ],
    course: "Portal Loop Optimization",
    status: "alive",
  },
  {
    id: 21,
    name: "Chell",
    birth: null,
    occupation: "Test Subject",
    traits: ["silent", "determined", "unusually resistant to neurotoxin"],
    course: "Advanced Portal Device Proficiency",
    status: "alive",
  },
  {
    id: 22,
    name: "Atlas",
    birth: null,
    occupation: "Cooperative Testing Robot",
    traits: ["loyal", "spherical", "slightly clumsy"],
    course: "Cooperative Testing Initiative (Blue Unit)",
    status: "alive",
  },
  {
    id: 23,
    name: "P-body",
    birth: null,
    occupation: "Cooperative Testing Robot",
    traits: ["tall", "curious", "fond of high fives"],
    course: "Cooperative Testing Initiative (Orange Unit)",
    status: "alive",
  },
];
